version: "3"
services:
    web:
        image: django
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        container_name: django
        # env_file: .env
        ports:
            - "80:8000"
        volumes:
            - .:/app
            - .:/members:/members
            - .:/static:/static
            - .:/templates:/templates
            - .:/tp69:/tp69
            - .:/manage.py:/manage.py

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "80:8000"
